apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - dashboard-tailscale.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 70.7.0
    namespace: monitoring
    releaseName: kube-prometheus-stack
    includeCRDs: true
    valuesFile: values-kube-prometheus-stack.yaml

resources:
  - ingress.yaml