grafana:
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      folderAnnotation: grafana_folder
      provider:
        foldersFromFilesStructure: true
  persistence:
    enabled: false
  admin:
    # existingSecret: "grafana-credentials"
    userKey: admin-user
    passwordKey: admin-password
  serviceMonitor:
    enabled: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "argocd"
          orgId: 1
          folder: "argocd"
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/argocd
  dashboards:
    argocd:
      # https://grafana.com/grafana/dashboards/19993-argocd-operational-overview/
      argocd-operational-overview:
        gnetId: 19993
        revision: 2
        datasource: prometheus
      # https://grafana.com/grafana/dashboards/19975-argocd-notifications-overview/
      argocd-notifications-overview:
        gnetId: 19975
        revision: 2
        datasource: prometheus
      # https://grafana.com/grafana/dashboards/19974-argocd-application-overview/
      argocd-application-overview:
        gnetId: 19974
        revision: 2
        datasource: prometheus
# prometheusOperator:
#   admissionWebhooks:
#     enabled: false
prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
    externalUrl: https://prometheus.rajsingh.info
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    enableRemoteWriteReceiver: true
    enableFeatures:
      - exemplar-storage
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 100Gi
  server:
    additionalScrapeConfigs:
      - job_name: opencost
        honor_labels: true
        scrape_interval: 1m
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: http
        dns_sd_configs:
          - names:
              - opencost.opencost
            type: "A"
            port: 9003
    retention: 30d

alertmanager:
  enabled: true

kubeProxy:
  enabled: false

kubeControllerManager:
  enabled: true

kubeScheduler:
  enabled: true
