grafana:
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      folderAnnotation: grafana_folder
      provider:
        foldersFromFilesStructure: true
  persistence:
    enabled: false
  admin:
    # existingSecret: "grafana-credentials"
    userKey: admin-user
    passwordKey: admin-password
  serviceMonitor:
    enabled: true
  # dashboardProviders:
  #   dashboardproviders.yaml:
  #     apiVersion: 1
  #     providers:
  #       - name: "tailscale"
  #         orgId: 1
  #         folder: "tailscale"
  #         type: file
  #         disableDeletion: false
  #         editable: true
  #         options:
  #           path: /var/lib/grafana/dashboards/tailscale
  # dashboards:
  #   argocd:
  #     # https://grafana.com/grafana/dashboards/19993-argocd-operational-overview/
  #     argocd-operational-overview:
  #       gnetId: 19993
  #       revision: 2
  #       datasource: prometheus
prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    enableRemoteWriteReceiver: true
    enableFeatures:
      - exemplar-storage
    retention: 30d
    storageSpec:
      emptyDir: {}

alertmanager:
  enabled: true

kubeProxy:
  enabled: true

kubeControllerManager:
  enabled: true

kubeScheduler:
  enabled: true
