apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    version: 1.80.3
    namespace: tailscale
    releaseName: tailscale-operator
    includeCRDs: true
    valuesInLine:
      apiServerProxyConfig:
        mode: "true"
      operatorConfig:
        hostname: "customderp-aws-eastus-operator"