apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: derper
spec:
  dnsNames:
    - "*.ec2.internal.customderp.rajsingh.info"
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: issuer
  secretName: derper-tls
  usages:
    - digital signature
    - key encipherment