apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudflare-ddns
  labels:
    app: cloudflare-ddns
spec:
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      containers:
        - name: cloudflare-ddns
          image: favonia/cloudflare-ddns:latest
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CLOUDFLARE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: derp-secret
                  key: CLOUDFLARE_API_TOKEN
            - name: DOMAINS
              value: "$(NODE_NAME).customderp.rajsingh.info"
            - name: PROXIED
              value: "false"
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000