---
apiVersion: v1
kind: ConfigMap
metadata:
  name: derpprobe
data:
  custom-derp.json: |
    {
    	"Regions": {
    		"900": {
    			"RegionID": 900,
    			"RegionCode": "customderp",
    			"RegionName": "Custom DERP",
    			"Nodes": [
    				{
    					"Name": "1",
    					"RegionID": 900,
    					"HostName": "ip-10-0-3-119.ec2.internal.customderp.rajsingh.info"
    				},
    				{
    					"Name": "2",
    					"RegionID": 900,
    					"HostName": "ip-10-0-2-81.ec2.internal.customderp.rajsingh.info"
    				}
    			]
    		}
    	}
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: derpprobe
  labels:
    app: derpprobe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: derpprobe
  template:
    metadata:
      labels:
        app: derpprobe
    spec:
      containers:
      - name: derpprobe
        image: ghcr.io/rajsinghtech/derpprobe:v0.0.1
        command: ["/bin/sh", "-c", "/usr/local/bin/derpprobe -derp-map=file:///config/custom-derp.json"]
        ports:
        - containerPort: 8030
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: derpprobe 
---
apiVersion: v1
kind: Service
metadata:
  name: derpprobe
spec:
  selector:
    app: derpprobe
  ports:
  - name: http
    port: 80
    targetPort: 8030
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: derpprobe-customderp
spec:
  ingressClassName: tailscale
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: derpprobe
            port:
              name: http
  tls:
  - hosts:
    - derpprobe
